spring:
  application:
    name: SOS Alert
  data:
    mongodb:
      uri: mongodb://localhost:27017/emergency_mentalwellbeingauthentication
  mail:
    host: smtp.gmail.com
    port: 587
    #username: # --- Add Email from which all emails are going to send ---
    #password: # --- Generate application password for that email id from google console ---

    username: codiescoder@gmail.com
    password: nhxvxwgsthvypwjq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8081